// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFv47753CDSyp5LNQCM9uf3l6Jo_tc-Ns',
    appId: '1:586630744414:web:7b6b1f1c62cfa2340ae7cf',
    messagingSenderId: '586630744414',
    projectId: 'thongbaogiasu',
    authDomain: 'thongbaogiasu.firebaseapp.com',
    storageBucket: 'thongbaogiasu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFdT58EYxYNRuwqXPQiChnd6eJbNYBp_U',
    appId: '1:586630744414:android:ba3673e125dcf6b00ae7cf',
    messagingSenderId: '586630744414',
    projectId: 'thongbaogiasu',
    storageBucket: 'thongbaogiasu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGdHc66Xi8KdO9hMHWN9kpbfY8yP7kD1g',
    appId: '1:586630744414:ios:f988da3ef9b657890ae7cf',
    messagingSenderId: '586630744414',
    projectId: 'thongbaogiasu',
    storageBucket: 'thongbaogiasu.firebasestorage.app',
    iosBundleId: 'com.example.khoaLuanTotNgiepGiaSuNguoiHoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGdHc66Xi8KdO9hMHWN9kpbfY8yP7kD1g',
    appId: '1:586630744414:ios:f988da3ef9b657890ae7cf',
    messagingSenderId: '586630744414',
    projectId: 'thongbaogiasu',
    storageBucket: 'thongbaogiasu.firebasestorage.app',
    iosBundleId: 'com.example.khoaLuanTotNgiepGiaSuNguoiHoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFv47753CDSyp5LNQCM9uf3l6Jo_tc-Ns',
    appId: '1:586630744414:web:263221786c187c360ae7cf',
    messagingSenderId: '586630744414',
    projectId: 'thongbaogiasu',
    authDomain: 'thongbaogiasu.firebaseapp.com',
    storageBucket: 'thongbaogiasu.firebasestorage.app',
  );
}
